---
version: '3'
services:
  cappuccino:
    image: ghcr.io/mikecao/cappuccino:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://cappuccino:cappuccino@db:5432/cappuccino
      DATABASE_TYPE: postgresql
      HASH_SALT: replace-me-with-a-random-string
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: cappuccino
      POSTGRES_USER: cappuccino
      POSTGRES_PASSWORD: cappuccino
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - cappuccino-db-data:/var/lib/postgresql/data
    restart: always
volumes:
  cappuccino-db-data:
